name: Enclave artifacts

# FLT(uoemai): Workflows run in the platform repository.
# on:
#   push:
#     branches: [ main ]

env:
  DOCKER_BUILD_ARGS: --cache-from type=gha --cache-to type=gha
  DOCKER_BUILDKIT: 1
  BUILDX_CONTAINER: container

jobs:
  build_release_enclave:
    name: Build release enclave
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Expose Docker environment variables for gha cache
        # This action takes in the ID tokens etc provided by the permissions,
        # as well as some environment data, and exposes them to future steps
        # in the correct locations and formats for their use with the `gha`
        # GitHub Actions cache for Docker.
        uses: crazy-max/ghaction-github-runtime@3cb05d89e1f492524af3d41a1c98c83bc3025124 # v3.1.0

      - name: Setup Docker
        run: docker buildx create --use --name container --driver docker-container

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Set up necessary SGX stuff
        run: sudo ./c/docker/sgx_runtime_libraries.sh

      - name: Build and test with Maven
        run: ./mvnw -e -B exec:exec@enclave-release

      - name: Get untracked artifacts
        id: artifacts
        run: |
            git ls-files --others --exclude-standard src/main/resources
            echo 'artifacts<<EOF' >> "$GITHUB_OUTPUT"
            git ls-files --others --exclude-standard src/main/resources >> "$GITHUB_OUTPUT"
            echo 'EOF' >> "$GITHUB_OUTPUT"

      -  name: Upload enclave and JNI shim
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
         with:
          name: enclave-and-jnishim
          path: ${{steps.artifacts.outputs.artifacts}}
